comprobantes:
    path:     /
    defaults: { _controller: "contabilidadBundle:comprobantes:index" }

comprobantes_show:
    path:     /{id}/show
    defaults: { _controller: "contabilidadBundle:comprobantes:show" }

comprobantes_new:
    path:     /new
    defaults: { _controller: "contabilidadBundle:comprobantes:new" }

comprobantes_create:
    path:     /create
    defaults: { _controller: "contabilidadBundle:comprobantes:create" }
    requirements: { _method: post }

comprobantes_edit:
    path:     /{id}/edit
    defaults: { _controller: "contabilidadBundle:comprobantes:edit" }

comprobantes_update:
    path:     /{id}/update
    defaults: { _controller: "contabilidadBundle:comprobantes:update" }
    requirements: { _method: post|put }

comprobantes_delete:
    path:     /{id}/delete
    defaults: { _controller: "contabilidadBundle:comprobantes:delete" }
    requirements: { _method: post|delete }
