cuentas:
    path:     /
    defaults: { _controller: "contabilidadBundle:cuentas:index" }

cuentas_show:
    path:     /{id}/show
    defaults: { _controller: "contabilidadBundle:cuentas:show" }

cuentas_new:
    path:     /new
    defaults: { _controller: "contabilidadBundle:cuentas:new" }

cuentas_create:
    path:     /create
    defaults: { _controller: "contabilidadBundle:cuentas:create" }
    requirements: { _method: post }

cuentas_edit:
    path:     /{id}/edit
    defaults: { _controller: "contabilidadBundle:cuentas:edit" }

cuentas_update:
    path:     /{id}/update
    defaults: { _controller: "contabilidadBundle:cuentas:update" }
    requirements: { _method: post|put }

cuentas_delete:
    path:     /{id}/delete
    defaults: { _controller: "contabilidadBundle:cuentas:delete" }
    requirements: { _method: post|delete }
