productoBundle\Entity\inventario:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        unidadM:
            type: string
            length: '20'
        existencia:
            type: string
            length: '15'
    lifecycleCallbacks: {  }
