facturacionBundle\Entity\llaves:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contenido:
            type: string
            length: 255 
    manyToOne:
        archivos:
          targetEntity: facturacionBundle\Entity\archivos
          inversedBy: llaves        
    lifecycleCallbacks: {  }
