archivos:
    path:     /
    defaults: { _controller: "facturacionBundle:archivos:index" }

archivos_show:
    path:     /{id}/show
    defaults: { _controller: "facturacionBundle:archivos:show" }

archivos_new:
    path:     /new
    defaults: { _controller: "facturacionBundle:archivos:new" }

archivos_create:
    path:     /create
    defaults: { _controller: "facturacionBundle:archivos:create" }
    requirements: { _method: post }

archivos_edit:
    path:     /{id}/edit
    defaults: { _controller: "facturacionBundle:archivos:edit" }

archivos_update:
    path:     /{id}/update
    defaults: { _controller: "facturacionBundle:archivos:update" }
    requirements: { _method: post|put }

archivos_delete:
    path:     /{id}/delete
    defaults: { _controller: "facturacionBundle:archivos:delete" }
    requirements: { _method: post|delete }
