customer:
    path:     /
    defaults: { _controller: "facturacionBundle:customer:index" }

customer_show:
    path:     /{id}/show
    defaults: { _controller: "facturacionBundle:customer:show" }

customer_new:
    path:     /new
    defaults: { _controller: "facturacionBundle:customer:new" }

customer_create:
    path:     /create
    defaults: { _controller: "facturacionBundle:customer:create" }
    requirements: { _method: post }

customer_edit:
    path:     /{id}/edit
    defaults: { _controller: "facturacionBundle:customer:edit" }

customer_update:
    path:     /{id}/update
    defaults: { _controller: "facturacionBundle:customer:update" }
    requirements: { _method: post|put }

customer_delete:
    path:     /{id}/delete
    defaults: { _controller: "facturacionBundle:customer:delete" }
    requirements: { _method: post|delete }
