producto:
    path:     /
    defaults: { _controller: "facturacionBundle:producto:index" }

producto_show:
    path:     /{id}/show
    defaults: { _controller: "facturacionBundle:producto:show" }

producto_new:
    path:     /new
    defaults: { _controller: "facturacionBundle:producto:new" }

producto_create:
    path:     /create
    defaults: { _controller: "facturacionBundle:producto:create" }
    requirements: { _method: post }

producto_edit:
    path:     /{id}/edit
    defaults: { _controller: "facturacionBundle:producto:edit" }

producto_update:
    path:     /{id}/update
    defaults: { _controller: "facturacionBundle:producto:update" }
    requirements: { _method: post|put }

producto_delete:
    path:     /{id}/delete
    defaults: { _controller: "facturacionBundle:producto:delete" }
    requirements: { _method: post|delete }
