facturacion:
    resource: "@facturacionBundle/Resources/config/routing.yml"
    prefix:   /

conta:
    resource: "@contabilidadBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
