<?php

namespace configuracionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * corporativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class corporativoRepository extends EntityRepository
{
}
