contabilidadBundle\Entity\polizas:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        version:
            type: string
            length: '100'        
        mes:
            type: string
            length: '10'
        anio:
            type: string
            length: '10'
    manyToOne:
        poliza:
          targetEntity: contabilidadBundle\Entity\poliza
          inversedBy: polizas        
          type: integer
    manyToOne:          
        empresa:
          targetEntity: contabilidadBundle\Entity\empresa
          inversedBy: polizas     
    lifecycleCallbacks: {  }
