contabilidadBundle\Entity\poliza:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        tipo:
            type: integer
        numero:
            type: string
            length: '50'
        fecha:
            type: date
        concepto:
            type: string
            length: '300'
    manyToOne:
        polizas:
            targetEntity: contabilidadBundle\Entity\polizas
            inversedBy: poliza               
    lifecycleCallbacks: {  }
