<?php

namespace contenidoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * misProductosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class misProductosRepository extends EntityRepository
{
}
